version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: transaction-history-service-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

