version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: transaction-analytic-service-db
    ports:
      - '2002:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

